import { features } from "process";

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const allBikes = [
  {
    model: "Vario 125",
    machine: {
      engineType: "Automatic",
      fuelSupplySystem: "PGM-FI (Programmed Fuel Injection)",
      displacement: "124,8 cc",
      boreAndStroke: "52,4 x 57,9 mm",
      compressionRatio: "11,0 : 1",
      transmissionType: "Otomatis , V - Matic",
      maximumPower: "8,2 kW (11,1 PS) / 8.500 rpm",
      maximumTorque: "10,8 Nm (1,1 kgf.m) / 5.000 rpm",
      starterType: "Elektrik",
      clutchType: "Automatic Sentrifugal, Tipe Kering",
      lubricantType: "0,8 liter (Penggantian Periodik)",
    },
    chassis: {
      frameType: "Underbone",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Swing Arm dengan suspensi Tunggal",
      frontTireSize: "90/80 – 14M/C 43 P Tubeless",
      rearTireSize: "100/80 - 14M/C 48P Tubeless",
      frontBrake: "Wavy Disc Brake",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System (CBS)",
    },
    dimension: {
      lengthWidthHeight: "1.918 x 679 x 1.066 mm",
      seatHeight: "769 mm",
      wheelbase: "1.280 mm",
      groundClearance: "131 mm",
      curbWeight: "111 kg",
    },
    capacities: {
      fuelTankCapacity: "5,5 liter",
      oilCapacity: "0,8 liter pada Penggantian Periodik",
      uBoxCapacity: "18 liter",
    },
    electrical: {
      batteryType: "MF 12V-5 Ah",
      ignitionSystem: "Full transisterized",
      sparkPlugType: "NGK CPR9EA-9 / Denso U27EPR9",
    },
    keyless: true,
    price: 23,
    image: "/bikes/vario125.png",
    colorVariant: [
      "/bikes/v125/v125-mblack.png",
      "/bikes/v125/v125-mblue.png",
      "/bikes/v125/v125-mred.png",
      "/bikes/v125/v125-rblack.png",
      "/bikes/v125/v125-smblack.png",
    ],
  },
  {
    model: "Vario 160",
    machine: {
      engineType: "Automatic",
      coolingSystem: "Pendingin Cairan",
      ignitionSystem: "PGM-FI (Programmed Fuel Injection)",
      displacement: "156,9 cc",
      boreStroke: "60 x 55,5 mm",
      compressionRatio: "12 : 1",
      maxPower: "11,3 kW (15,4 PS) / 8.500 rpm",
      maxTorque: "13,8 Nm (1,4 kgf,m) / 7.000 rpm",
      transmissionType: "Otomatis, V-Matic",
      starterType: "Elektrik",
      clutchType: "Otomatis, Sentrifugal, Tipe Kering",
      oilType: "Basah",
      oilCapacity: "0,8 liter (Penggantian Periodik)",
    },
    chassis: {
      frameType: "Underbone - eSAF (enhanced Smart Architecture Frame)",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Swing Arm dengan Suspensi Tunggal",
      frontTireSize: "100/80 - 14M/C Tubeless",
      rearTireSize: "120/70 - 14M/C Tubeless",
      frontBrake:
        "Vario 160 Tipe ABS - 220 mm Cakram Hidrolik / Vario 160 Tipe CBS - 190 mm Cakram Hidrolik",
      rearBrake:
        "Vario 160 Tipe ABS - 220 mm Cakram Hidrolik / Vario 160 Tipe CBS - Tromol",
      brakingSystem:
        "Combi Brake System (CBS) & Anti-Lock Braking System (ABS)",
    },
    dimension: {
      lengthWidthHeight: "1.929 x 679 x 1.088 mm",
      seatHeight: "778 mm",
      wheelbase: "1.277 mm",
      groundClearance: "140 mm",
      curbWeight: "115 kg (CBS) & 117 kg (ABS)",
    },
    capacities: {
      fuelTankCapacity: "5,5 liter",
    },
    electrical: {
      batteryType: "MF 12V-5 Ah",
      ignitionSystem: "Full Transisterized",
      sparkPlugType: "NGK LMAR8L-9",
    },
    keyless: true,
    price: 27,
    image: "/bikes/vario160.png",
    colorVariant: [
      "/bikes/v160/v160-mblack.png",
      "/bikes/v160/v160-mblackcbs.png",
      "/bikes/v160/v160-mblackcbs2.png",
      "/bikes/v160/v160-mblue.png",
      "/bikes/v160/v160-mbluecbs.png",
      "/bikes/v160/v160-mred.png",
      "/bikes/v160/v160-mwhite.png",
      "/bikes/v160/v160-mwhitecbs.png",
    ],
  },
  {
    model: "BeAT",
    machine: {
      engineType: "Automatic",
      coolingSystem: "N/A", // Assuming no specific cooling system provided
      ignitionSystem: "Full Transisterized",
      displacement: "109,5 cc",
      boreStroke: "47.0 x 63.1 mm",
      compressionRatio: "10,0 : 1",
      maxPower: "6.6 kW (9.0 PS) / 7.500 rpm",
      maxTorque: "9.2 N.m (0.94 kgf.m) / 6000 rpm",
      transmissionType: "Otomatis, V-Matic",
      starterType:
        "Elektrik dan Kick Starter (Tipe CBS), Elektrik (Tipe Deluxe & Deluxe Smart Key)",
      clutchType: "Otomatis, Sentrifugal, Tipe Kering",
      oilType: "N/A", // Assuming no specific oil type provided
      oilCapacity: "N/A", // Assuming no specific oil capacity provided
    },
    chassis: {
      frameType: "Tulang Punggung – eSAF (enhance Smart Architecture Frame)",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Lengan Ayun dengan Peredam Kejut Tunggal",
      frontTireSize: "80/90 - 14 M/C 40P Tubeless",
      rearTireSize: "90/90 - 14 M/C 46P Tubeless",
      frontBrake: "Cakram Hidrolik dengan Piston Tunggal",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System",
    },
    dimension: {
      lengthWidthHeight: "1876 x 669 x 1080 mm",
      seatHeight: "742 mm",
      wheelbase: "1.255 mm",
      groundClearance: "148 mm",
      curbWeight: "88 kg (tipe CBS), 87 kg (tipe Deluxe & Deluxe Smart Key)",
    },
    capacities: {
      fuelTankCapacity: "4.2 L",
      oilCapacity: "0.65 Liter (Penggantian Periodik)",
      uBoxCapacity: "N/A", // Assuming no U-Box capacity provided
    },
    electrical: {
      batteryType:
        "MF 12V-3Ah (Tipe CBS) / MF 12V-5Ah (Tipe Deluxe & Deluxe Smart Key)",
      ignitionSystem: "Full Transisterized", // Assuming ignition system is still Full Transisterized
      sparkPlugType: "N/A", // Assuming no specific spark plug type provided in this update
    },
    keyless: false,
    price: 18,
    image: "/bikes/beat.png",
    colorVariant: [
      "/bikes/beat/beat-black.png",
      "/bikes/beat/beat-mblack.png",
      "/bikes/beat/beat-mblue.png",
      "/bikes/beat/beat-mgreen.png",
      "/bikes/beat/beat-msilver.png",
      "/bikes/beat/beat-rblack.png",
      "/bikes/beat/beat-rckblack.png",
      "/bikes/beat/beat-wblack.png",
    ],
  },
  {
    model: "BeAT Street",
    machine: {
      engineType: "Automatic",
      coolingSystem: "N/A", // Assuming no specific cooling system provided
      ignitionSystem: "Full Transisterized",
      displacement: "109,5 cc",
      boreStroke: "47,0 x 63,1 mm",
      compressionRatio: "10,0 : 1",
      maxPower: "6.6 kW (9.0 PS) / 7.500 rpm",
      maxTorque: "9.2 N.m (0.94 kgf.m) / 6000 rpm",
      transmissionType: "Otomatis, V-Matic",
      starterType: "Elektrik",
      clutchType: "Otomatis, Sentrifugal, Tipe Kering",
      oilType: "N/A", // Assuming no specific oil type provided
      oilCapacity: "N/A", // Assuming no specific oil capacity provided
    },
    chassis: {
      frameType: "Tulang Punggung - eSAF (enhance Smart Architecture Frame)",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Lengan Ayun dengan Peredam Kejut Tunggal",
      frontTireSize: "100/90 - 12 59J Tubeless",
      rearTireSize: "110/90 – 12 64J Tubeless",
      frontBrake: "Cakram Hidrolik, Piston Tunggal",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System",
    },
    dimension: {
      lengthWidthHeight: "1868 x 745 x 1058 mm",
      seatHeight: "742 mm",
      wheelbase: "1.251 mm",
      groundClearance: "148 mm",
      curbWeight: "89 kg",
    },
    capacities: {
      fuelTankCapacity: "4,2 L",
      oilCapacity: "0,65 liter pada Penggantian Periodik",
      uBoxCapacity: "N/A", // Assuming no U-Box capacity provided
    },
    electrical: {
      batteryType: "MF 12V-3Ah",
      ignitionSystem: "N/A", // Assuming no specific ignition system provided in this update
      sparkPlugType: "N/A", // Assuming no specific spark plug type provided
    },
    keyless: false,
    price: 19,
    image: "/bikes/beat-street.png",
    colorVariant: [
      "/bikes/beat-street/beat-street-black.png",
      "/bikes/beat-street/beat-street-brown.png",
    ],
  },
  {
    model: "Genio",
    machine: {
      engineType: "Automatic",
      coolingSystem: "N/A", // Assuming no specific cooling system provided
      ignitionSystem: "N/A", // Assuming no specific ignition system provided
      displacement: "109,5 cc", // Volume Langkah, if assumed similar from previous entries
      boreStroke: "47,0 x 63,1 mm",
      compressionRatio: "10,0 : 1",
      maxPower: "6,6 kW (9,0 PS) / 7.500 rpm",
      maxTorque: "9,3 Nm (0,95 kgf.m) / 5.500 rpm",
      transmissionType: "Automatic, V-Matic",
      starterType: "Elektrik dan Kick Starter",
      clutchType: "Automatic Centrifugal Clutch Dry Type",
      oilType: "N/A", // Assuming no specific oil type provided
      oilCapacity: "N/A", // Assuming no specific oil capacity provided
    },
    chassis: {
      frameType: "Underbone – eSAF (Enhanced Smart Architecture Frame)",
      frontSuspensionType: "Telescopic",
      rearSuspensionType: "Swing Arm dengan Suspensi Tunggal",
      frontTireSize: "100/90 – 12 59J (Tubeless)",
      rearTireSize: "110/90 – 12 64J (Tubeless)",
      frontBrake: "Cakram Hidrolik Piston Tunggal",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System",
    },
    dimension: {
      lengthWidthHeight: "1.862 x 694 x 1.061 mm",
      seatHeight: "744 mm",
      wheelbase: "1.251 mm",
      groundClearance: "150 mm",
      curbWeight: "92 kg (Tipe CBS), 93 kg (Tipe CBS - ISS)",
    },
    capasities: {
      fuelTankCapacity: "4,2 L",
      oilCapacity: "0,65 L (Penggantian Periodik)",
      uBoxCapacity: "N/A", // Assuming no U-Box capacity provided
    },
    electrical: {
      batteryType: "MF 12 V – 3Ah (Tipe CBS), MF 12 V – 5 Ah (Tipe CBS – ISS)",
      ignitionSystem: "Full Transisterized",
      sparkPlugType: "NGK MR9C-9N",
    },
    keyless: false,
    price: 19,
    image: "/bikes/genio.png",
    colorVariant: [
      "/bikes/genio/fblack.png",
      "/bikes/genio/fblue.png",
      "/bikes/genio/fgreen.png",
      "/bikes/genio/rblack.png",
      "/bikes/genio/redblack.png",
      "/bikes/genio/rsblack.png",
    ],
  },
  {
    model: "Scoopy",
    machine: {
      engineType: "Automatic",
      coolingSystem: "Pendingin Udara", // Added based on new information
      ignitionSystem: "Full Transisterized", // Assuming this remains consistent
      displacement: "N/A", // Assuming no specific displacement provided
      boreStroke: "47 x 63,1 mm",
      compressionRatio: "10 : 1",
      maxPower: "6,6 kW (9 PS) / 7.500 rpm",
      maxTorque: "9,3 Nm (0,95 kgf.m) / 5.500 rpm",
      transmissionType: "Otomatis, V-Matic",
      starterType: "Elektrik & kick Starter / Elektrik (Tipe Smart Key)",
      clutchType: "Otomatis, Sentrifugal, Tipe Kering",
      oilType: "N/A", // Assuming no specific oil type provided
      oilCapacity: "N/A", // Assuming no specific oil capacity provided
    },
    chassis: {
      frameType: "Underbone - eSAF (enhance Smart Architecture Frame)",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Lengan Ayun dengan Peredam Kejut Tunggal",
      frontTireSize: "100/90 – 12 59J (Tubeless)",
      rearTireSize: "110/90 – 12 64J (Tubeless)",
      frontBrake: "Cakram Hidrolik dengan Piston Tunggal",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System",
    },
    dimension: {
      lengthWidthHeight: "1.864 x 683 x 1.075 mm",
      seatHeight: "746 mm",
      wheelbase: "1.251 mm",
      groundClearance: "145 mm",
      curbWeight: "95 kg dan 94 kg (tipe SmartKey)",
    },
    capasities: {
      fuelTankCapacity: "4,2 L",
      oilCapacity: "0,65 Liter (Penggantian Periodik)",
      uBoxCapacity: "N/A", // Assuming no U-Box capacity provided
    },
    electrical: {
      batteryType: "MF 12V-5Ah",
      ignitionSystem: "Full Transisterized",
      sparkPlugType: "NGK MR9C-9N",
    },
    keyless: true,
    price: 22,
    image: "/bikes/scoopy.png",
    colorVariant: [
      "/bikes/scoopy/fblue.png",
      "/bikes/scoopy/fbrown.png",
      "/bikes/scoopy/pblack.png",
      "/bikes/scoopy/pwhite.png",
      "/bikes/scoopy/sgreen.png",
      "/bikes/scoopy/sgrey.png",
      "/bikes/scoopy/sred.png",
      "/bikes/scoopy/sreds.png",
    ],
  },
  {
    model: "Stylo 160",
    machine: {
      engineType: "Automatic",
      coolingSystem: "Pendingin Cairan",
      ignitionSystem: "N/A", // Assuming this remains unspecified
      displacement: "156,9 cc",
      boreStroke: "60 x 55,5 mm",
      compressionRatio: "12:1",
      maxPower: "11,3 kW (15,4 PS) / 8,500 rpm",
      maxTorque: "13,8 Nm (1,5 kgf.m) / 7000 rpm",
      transmissionType: "Otomatis, V-Matic",
      starterType: "Elektrik",
      clutchType: "Otomatis, Sentrifugal, Tipe Kering",
      oilType: "Basah",
      oilCapacity: "0,8 liter (Penggantian Periodik)",
    },
    chassis: {
      frameType: "Underbone - eSAF (enhanced Smart Architecture Frame)",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Swing Arm dengan Suspensi Tunggal",
      frontTireSize: "110/90 - 12 M/C Tubeless",
      rearTireSize: "130/80 - 12 M/C Tubeless",
      frontBrake:
        "Stylo 160 Tipe ABS - 220 mm Cakram Hidrolik, Stylo 160 Tipe CBS - 190 mm Cakram Hidrolik",
      rearBrake:
        "Stylo 160 Tipe ABS - 220 mm Cakram Hidrolik, Stylo 160 Tipe CBS - Tromol",
      brakingSystem:
        "Anti-Lock Braking System (ABS) & Combi Brake System (CBS)",
    },
    dimesion: {
      lengthWidthHeight:
        "1.886 x 706 x 1.133 mm (ABS) & 1.886 x 701 x 1.133 mm (CBS)",
      seatHeight: "768 mm",
      wheelbase: "1.275 mm",
      groundClearance: "151 mm",
      curbWeight: "118 kg (ABS) & 115 kg (CBS)",
    },
    electrical: {
      batteryType: "MF 12V-5Ah",
      ignitionSystem: "Full Transisterized",
      sparkPlugType: "NGK LMAP8L-9",
      chargerPower: "5V, 2.1A",
    },
    keyles: true,
    price: 28,
    image: "/bikes/stylo.png",
    colorVariant: [
      "/bikes/stylo/gbeige.png",
      "/bikes/stylo/gblack.png",
      "/bikes/stylo/gred.png",
      "/bikes/stylo/mblack.png",
      "/bikes/stylo/mwhite.png",
      "/bikes/stylo/rgreen.png",
    ],
  },
  {
    model: "PCX 160",
    machine: {
      engineType: "Automatic",
      coolingType: "Pendingin Cairan",
      fuelSupplySystem: "PGM-FI (Programmed Fuel Injection)",
      strokeVolume: "156,9 cc",
      diameterStroke: "60 x 55,5 mm",
      compressionRatio: "12:1",
      maxPower: "11,8 kW (16 PS) / 8.500 rpm",
      maxTorque: "14,7 Nm (1,5 kgf.m) / 6.500 rpm",
      transmissionType: "Otomatis, V-Matic",
      starterType: "Elektrik",
      clutchType: "Otomatis, Sentrifugal, Tipe Kering",
      oilCapacity: "0,8 liter (Penggantian Periodik)",
    },
    chassis: {
      frameType: "Double Cradle",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Suspensi Belakang Ganda",
      frontTireSize: "110/70 - 14 M/C Tubeless",
      rearTireSize: "130/70 - 13 M/C Tubeless",
      frontBrake: "Cakram Hidrolik - (Tipe CBS) TriplePots Hydraulic",
      rearBrake: "Cakram Hidrolik",
      brakingSystem:
        "(Tipe CBS) Combined Brake System / (Tipe ABS) Anti Lock Braking System",
    },
    dimension: {
      length: "1.936 mm",
      width: "742 mm",
      height: "1.108 mm",
      wheelbase: "1.313 mm",
      groundClearance: "135 mm",
      seatHeight: "764 mm",
      curbWeight: "131 kg (tipe CBS), 132 kg (tipe ABS)",
      fuelTankCapacity: "8,1 liter",
    },
    electrical: {
      ignitionSystem: "Full Transisterized",
      batteryType: "12 V - 5 Ah, tipe MF",
      sparkPlugType: "NGKLMAR8L-9",
      powerCharger: "5V, 2.1A",
    },
    keyless: true,
    price: 33,
    image: "/bikes/pcx.png",
    colorVariant: [
      "/bikes/pcx/bblack.png",
      "/bikes/pcx/mblack.png",
      "/bikes/pcx/mblue.png",
      "/bikes/pcx/mbrown.png",
      "/bikes/pcx/mmred.png",
      "/bikes/pcx/mred.png",
      "/bikes/pcx/msilver.png",
      "/bikes/pcx/rmblue.png",
      "/bikes/pcx/wwhite.png",
      "/bikes/pcx/wwhitecbs.png",
    ],
  },
  {
    model: "ADV 160",
    machine: {
      engineType: "Automatic",
      coolingType: "Pendingin Cairan",
      fuelSupplySystem: "PGM-FI (Programmed Fuel Injection)",
      strokeVolume: "156,9 cc",
      diameterStroke: "60 x 55,5 mm",
      compressionRatio: "12 : 1",
      maxPower: "11,8 kW (16 PS) / 8.500 rpm",
      maxTorque: "14,7 Nm (1,5 kgf.m) / 6.500 rpm",
      transmissionType: "Otomatis, V-Matic",
      starterType: "Elektrik",
      clutchType: "Otomatis, Sentrifugal, Tipe Kering",
      lubricantType: "Basah",
      lubricantCapacity: "0,75 liter (Penggantian Periodik)",
    },
    chassis: {
      frameType: "Double Cradle",
      frontTireSize: "110/80 - 14M/C Tubeless",
      rearTireSize: "130/70 - 13M/C Tubeless",
      frontBrakeType: "Wavy Disc Brake",
      rearBrakeType: "Wavy Disc Brake",
      brakingSystem:
        "Triple Pots Hydraulic Combi Brake System (CBS) / Anti-Lock Braking System (ABS)",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Suspensi Belakang Ganda dengan Tabung",
    },
    dimension: {
      lengthWidthHeight: "1.950 x 763 x1.196 mm",
      seatHeight: "780 mm",
      wheelbase: "1.324 mm",
      groundClearance: "165 mm",
      curbWeight: "	133 kg (CBS & ABS)",
    },
    electrical: {
      batteryType: "MF 12V-5Ah",
      ignitionSystem: "Full Transisterized",
      sparkPlugType: "NGK LMAR8L-9",
    },
    keyless: true,
    price: 36,
    image: "/bikes/adv.png",
    colorVariant: [
      "/bikes/adv/dblack.png",
      "/bikes/adv/dgray.png",
      "/bikes/adv/dred.png",
      "/bikes/adv/dwhite.png",
      "/bikes/adv/mblack.png",
      "/bikes/adv/mbrown.png",
      "/bikes/adv/mred.png",
      "/bikes/adv/mwhite.png",
    ],
  },
  {
    model: "Forza",
    machine: {
      engineType: "Automatic",
      displacement: 249,
      fuelSupplySystem: "Fuel Injection (PGM-FI)",
      boreStroke: "67 x 70.7 mm",
      transmissionType: "Otomatis",
      compressionRatio: "10.2 : 1",
      maxPower: "17 kW / 7,750 rpm",
      maxTorque: "24 Nm / 6,250 rpm",
      starterType: "Elektrik",
      clutchType: "Automatic Centrifugal Clutch Dry Type",
      coolingSystem: "Pendinginan Cairan",
    },
    chassis: {
      frameType: "Under bone type",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Swing arm dengan suspensi ganda",
      frontTireSize: "120/70-15M/C 56P",
      rearTireSize: "140/70-14M/C 62P",
      frontBrakeType: "Hidrolis, single 256mm disc - ABS",
      rearBrakeType: "Hidrolis, single 240mm disc - ABS",
      brakingSystem: "ABS",
    },
    dimension: {
      lengthWidthHeight: "2.145x 750 x 1.360 mm",
      seatHeight: "780 mm",
      wheelbase: "1.510 mm",
      groundClearance: "145 mm",
      curbWeight: "186 Kg",
    },
    capacities: {
      fuelTankCapacity: "11,7 L",
      oilCapacity: "1,3 L (penggantian periodik)",
    },
    electrical: {
      batteryType: "12 V - 8,6 Ah (10h), MF-Wet Type",
      ignitionSystem: "Full transisterized",
      sparkPlugType: "NGK LMAR8A-9",
    },
    price: 90,
    image: "/bikes/forza.png",
    colorVariant: [
      "/bikes/forza/black.png",
      "/bikes/forza/blue.png",
      "/bikes/forza/grey.png",
      "/bikes/forza/red.png",
    ],
  },
];

export const evBike = [
  {
    model: "ICON e:",
    machine: {
      maximumPower: "1,7 kW/540 rpm",
      maximumTorque: "90 Nm/25 rpm",
      ratedPower: "0,58 kW",
    },
    chassis: {
      frameType: "Underbone",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Suspensi Belakang Ganda",
      frontTireSize: "90/90 - 12 443",
      rearTireSize: "	100/90 - 10 563",
      frontBrake: "Cakram Hidrolik",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System (CBS)",
    },
    dimension: {
      lengthWidthHeight: "1.918 x 679 x 1.066 mm",
      seatHeight: "769 mm",
      wheelbase: "1.280 mm",
      groundClearance: "131 mm",
      curbWeight: "111 kg",
    },
    capacities: {
      fuelTankCapacity: "5,5 liter",
      oilCapacity: "0,8 liter pada Penggantian Periodik",
      uBoxCapacity: "18 liter",
    },
    electrical: {
      batteryType: "MF 12V-5 Ah",
      ignitionSystem: "Full transisterized",
      sparkPlugType: "NGK CPR9EA-9 / Denso U27EPR9",
    },
    keyless: true,
    price: 23,
    image: "/bikes/icon.png",
    colorVariant: [
      "/bikes/icon/black.png",
      "/bikes/icon/mint.png",
      "/bikes/icon/orange.png",
      "/bikes/icon/red.png",
      "/bikes/icon/white.png",
    ],
  },
  {
    model: "EM1 e: & EM1 e: PLUS",
    machine: {
      maximumPower: "1.81 kW / 618 rpm",
      maximumTorque: "85 Nm / 110 rpm",
      ratedPower: "	1.5 kW",
    },
    chassis: {
      frameType: "Underbone",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Suspensi Belakang Ganda",
      frontTireSize: "90/90 - 12 443",
      rearTireSize: "	100/90 - 10 563",
      frontBrake: "Cakram Hidrolik",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System (CBS)",
    },
    dimension: {
      lengthWidthHeight: "1.918 x 679 x 1.066 mm",
      seatHeight: "769 mm",
      wheelbase: "1.280 mm",
      groundClearance: "131 mm",
      curbWeight: "111 kg",
    },
    capacities: {
      fuelTankCapacity: "5,5 liter",
      oilCapacity: "0,8 liter pada Penggantian Periodik",
      uBoxCapacity: "18 liter",
    },
    electrical: {
      batteryType: "MF 12V-5 Ah",
      ignitionSystem: "Full transisterized",
      sparkPlugType: "NGK CPR9EA-9 / Denso U27EPR9",
    },
    keyless: true,
    price: 23,
    image: "/bikes/em1.png",
    colorVariant: [
      "/bikes/em1/mblack.png",
      "/bikes/em1/msilver.png",
      "/bikes/em1/sred.png",
      "/bikes/em1/white.png",
    ],
  },
  {
    model: "CUV e: & RoadSync Duo",
    machine: {
      maximumPower: "1.81 kW / 618 rpm",
      maximumTorque: "85 Nm / 110 rpm",
      ratedPower: "	1.5 kW",
    },
    chassis: {
      frameType: "Underbone",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Suspensi Belakang Ganda",
      frontTireSize: "90/90 - 12 443",
      rearTireSize: "	100/90 - 10 563",
      frontBrake: "Cakram Hidrolik",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System (CBS)",
    },
    dimension: {
      lengthWidthHeight: "1.918 x 679 x 1.066 mm",
      seatHeight: "769 mm",
      wheelbase: "1.280 mm",
      groundClearance: "131 mm",
      curbWeight: "111 kg",
    },
    capacities: {
      fuelTankCapacity: "5,5 liter",
      oilCapacity: "0,8 liter pada Penggantian Periodik",
      uBoxCapacity: "18 liter",
    },
    electrical: {
      batteryType: "MF 12V-5 Ah",
      ignitionSystem: "Full transisterized",
      sparkPlugType: "NGK CPR9EA-9 / Denso U27EPR9",
    },
    keyless: true,
    price: 23,
    image: "/bikes/cuv.png",
    colorVariant: [
      "/bikes/cuv/mblack.png",
      "/bikes/cuv/msilver.png",
      "/bikes/cuv/mwhite.png",
      "/bikes/cuv/qmblack.png",
      "/bikes/cuv/qmsilver.png",
      "/bikes/cuv/qmwhite.png",
    ],
  },
];

export const sportBike = [
  {
    model: "CB150 Verza",
    machine: {
      maximumPower: "1,7 kW/540 rpm",
      maximumTorque: "90 Nm/25 rpm",
      ratedPower: "0,58 kW",
    },
    chassis: {
      frameType: "Underbone",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Suspensi Belakang Ganda",
      frontTireSize: "90/90 - 12 443",
      rearTireSize: "	100/90 - 10 563",
      frontBrake: "Cakram Hidrolik",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System (CBS)",
    },
    dimension: {
      lengthWidthHeight: "1.918 x 679 x 1.066 mm",
      seatHeight: "769 mm",
      wheelbase: "1.280 mm",
      groundClearance: "131 mm",
      curbWeight: "111 kg",
    },
    capacities: {
      fuelTankCapacity: "5,5 liter",
      oilCapacity: "0,8 liter pada Penggantian Periodik",
      uBoxCapacity: "18 liter",
    },
    electrical: {
      batteryType: "MF 12V-5 Ah",
      ignitionSystem: "Full transisterized",
      sparkPlugType: "NGK CPR9EA-9 / Denso U27EPR9",
    },
    keyless: true,
    price: 22,
    image: "/bikes/verza.png",
    colorVariant: [
      "/bikes/verza/black.png",
      "/bikes/verza/red.png",
      "/bikes/verza/mblack.png",
    ],
  },
  {
    model: "CB150R Streetfire",
    machine: {
      maximumPower: "1,7 kW/540 rpm",
      maximumTorque: "90 Nm/25 rpm",
      ratedPower: "0,58 kW",
    },
    chassis: {
      frameType: "Underbone",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Suspensi Belakang Ganda",
      frontTireSize: "90/90 - 12 443",
      rearTireSize: "	100/90 - 10 563",
      frontBrake: "Cakram Hidrolik",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System (CBS)",
    },
    dimension: {
      lengthWidthHeight: "1.918 x 679 x 1.066 mm",
      seatHeight: "769 mm",
      wheelbase: "1.280 mm",
      groundClearance: "131 mm",
      curbWeight: "111 kg",
    },
    capacities: {
      fuelTankCapacity: "5,5 liter",
      oilCapacity: "0,8 liter pada Penggantian Periodik",
      uBoxCapacity: "18 liter",
    },
    electrical: {
      batteryType: "MF 12V-5 Ah",
      ignitionSystem: "Full transisterized",
      sparkPlugType: "NGK CPR9EA-9 / Denso U27EPR9",
    },
    keyless: true,
    price: 31,
    image: "/bikes/cb150r.png",
    colorVariant: [
      "/bikes/cb150r/black.png",
      "/bikes/cb150r/mblack.png",
      "/bikes/cb150r/mgrey.png",
      "/bikes/cb150r/mred.png",
      "/bikes/cb150r/rblack.png",
    ],
  },
  {
    model: "CB150X",
    machine: {
      maximumPower: "1,7 kW/540 rpm",
      maximumTorque: "90 Nm/25 rpm",
      ratedPower: "0,58 kW",
    },
    chassis: {
      frameType: "Underbone",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Suspensi Belakang Ganda",
      frontTireSize: "90/90 - 12 443",
      rearTireSize: "	100/90 - 10 563",
      frontBrake: "Cakram Hidrolik",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System (CBS)",
    },
    dimension: {
      lengthWidthHeight: "1.918 x 679 x 1.066 mm",
      seatHeight: "769 mm",
      wheelbase: "1.280 mm",
      groundClearance: "131 mm",
      curbWeight: "111 kg",
    },
    capacities: {
      fuelTankCapacity: "5,5 liter",
      oilCapacity: "0,8 liter pada Penggantian Periodik",
      uBoxCapacity: "18 liter",
    },
    electrical: {
      batteryType: "MF 12V-5 Ah",
      ignitionSystem: "Full transisterized",
      sparkPlugType: "NGK CPR9EA-9 / Denso U27EPR9",
    },
    keyless: true,
    price: 34,
    image: "/bikes/cb150x.png",
    colorVariant: [
      "/bikes/cb150x/mblack.png",
      "/bikes/cb150x/mbrown.png",
      "/bikes/cb150x/mgreen.png",
      "/bikes/cb150x/red.png",
    ],
  },
];

export const cubBike = [
  {
    model: "Revo",
    machine: {
      maximumPower: "1,7 kW/540 rpm",
      maximumTorque: "90 Nm/25 rpm",
      ratedPower: "0,58 kW",
    },
    chassis: {
      frameType: "Underbone",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Suspensi Belakang Ganda",
      frontTireSize: "90/90 - 12 443",
      rearTireSize: "	100/90 - 10 563",
      frontBrake: "Cakram Hidrolik",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System (CBS)",
    },
    dimension: {
      lengthWidthHeight: "1.918 x 679 x 1.066 mm",
      seatHeight: "769 mm",
      wheelbase: "1.280 mm",
      groundClearance: "131 mm",
      curbWeight: "111 kg",
    },
    capacities: {
      fuelTankCapacity: "5,5 liter",
      oilCapacity: "0,8 liter pada Penggantian Periodik",
      uBoxCapacity: "18 liter",
    },
    electrical: {
      batteryType: "MF 12V-5 Ah",
      ignitionSystem: "Full transisterized",
      sparkPlugType: "NGK CPR9EA-9 / Denso U27EPR9",
    },
    keyless: true,
    price: 16,
    image: "/bikes/revo.png",
    colorVariant: [
      "/bikes/revo/ared.png",
      "/bikes/revo/black.png",
      "/bikes/revo/blue.png",
      "/bikes/revo/red.png",
    ],
  },
  {
    model: "Supra X 125 FI",
    machine: {
      maximumPower: "1,7 kW/540 rpm",
      maximumTorque: "90 Nm/25 rpm",
      ratedPower: "0,58 kW",
    },
    chassis: {
      frameType: "Underbone",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Suspensi Belakang Ganda",
      frontTireSize: "90/90 - 12 443",
      rearTireSize: "	100/90 - 10 563",
      frontBrake: "Cakram Hidrolik",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System (CBS)",
    },
    dimension: {
      lengthWidthHeight: "1.918 x 679 x 1.066 mm",
      seatHeight: "769 mm",
      wheelbase: "1.280 mm",
      groundClearance: "131 mm",
      curbWeight: "111 kg",
    },
    capacities: {
      fuelTankCapacity: "5,5 liter",
      oilCapacity: "0,8 liter pada Penggantian Periodik",
      uBoxCapacity: "18 liter",
    },
    electrical: {
      batteryType: "MF 12V-5 Ah",
      ignitionSystem: "Full transisterized",
      sparkPlugType: "NGK CPR9EA-9 / Denso U27EPR9",
    },
    keyless: true,
    price: 19,
    image: "/bikes/suprax.png",
    colorVariant: [
      "/bikes/suprax/black.png",
      "/bikes/suprax/mblack.png",
      "/bikes/suprax/red.png",
    ],
  },
  {
    model: "GTR 150",
    machine: {
      maximumPower: "1,7 kW/540 rpm",
      maximumTorque: "90 Nm/25 rpm",
      ratedPower: "0,58 kW",
    },
    chassis: {
      frameType: "Underbone",
      frontSuspensionType: "Teleskopik",
      rearSuspensionType: "Suspensi Belakang Ganda",
      frontTireSize: "90/90 - 12 443",
      rearTireSize: "	100/90 - 10 563",
      frontBrake: "Cakram Hidrolik",
      rearBrake: "Tromol",
      brakingSystem: "Combi Brake System (CBS)",
    },
    dimension: {
      lengthWidthHeight: "1.918 x 679 x 1.066 mm",
      seatHeight: "769 mm",
      wheelbase: "1.280 mm",
      groundClearance: "131 mm",
      curbWeight: "111 kg",
    },
    capacities: {
      fuelTankCapacity: "5,5 liter",
      oilCapacity: "0,8 liter pada Penggantian Periodik",
      uBoxCapacity: "18 liter",
    },
    electrical: {
      batteryType: "MF 12V-5 Ah",
      ignitionSystem: "Full transisterized",
      sparkPlugType: "NGK CPR9EA-9 / Denso U27EPR9",
    },
    keyless: true,
    price: 25,
    image: "/bikes/supragtr.png",
    colorVariant: [
      "/bikes/supragtr/black.png",
      "/bikes/supragtr/mred.png",
      "/bikes/supragtr/msilver.png",
      "/bikes/supragtr/red.png",
    ],
  },
];

export const bikeType = [
  {
    title: "Tipe",
    value: "",
  },
  {
    title: "Matic",
    value: "Matic",
  },
  {
    title: "Sport",
    value: "Sport",
  },
  {
    title: "Cub",
    value: "Cub",
  },
  {
    title: "Ev",
    value: "Ev",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
