import { features } from "process";

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const allBikes = [
  {
    model: "Vario 125",
    spec: {
      engineType: "4-Langkah, SOHC, eSP, Pendinginan Cairan",
      displacement: "124,8 cc",
      maxPower: "8,2 kW (11,1 PS) / 8.500 rpm",
      maxTorque: "10,8 Nm (1,1 kgf.m) / 5.000 rpm",
      brakingSystem: "Combi Brake System (CBS)",
    },
    transmissionType: "Otomatis",
    keyless: true,
    price: 23,
    image: "/bikes/vario125.png",
    colorVariant: [
      "/bikes/v125/v125-matteblack.png",
      "/bikes/v125/v125-matteblue.png",
      "/bikes/v125/v125-mattered.png",
      "/bikes/v125/v125-black.png",
      "/bikes/v125/v125-redblack.png",
    ],
  },
  {
    model: "Vario 160",
    spec: {
      engineType: "4 Langkah, 4-Valve, eSP+",
      displacement: "156,9 cc",
      maxPower: "11,3 kW (15,4 PS) / 8.500 rpm",
      maxTorque: "13,8 Nm (1,4 kgf,m) / 7.000 rpm",
      brakingSystem: "CBS / ABS",
    },
    transmissionType: "Otomatis",
    keyless: true,
    price: 27,
    image: "/bikes/vario160.png",
    colorVariant: [
      "/bikes/v160/v160-mblack.png",
      "/bikes/v160/v160-mblackcbs.png",
      "/bikes/v160/v160-mblackcbs2.png",
      "/bikes/v160/v160-mblue.png",
      "/bikes/v160/v160-mbluecbs.png",
      "/bikes/v160/v160-mred.png",
      "/bikes/v160/v160-mwhite.png",
      "/bikes/v160/v160-mwhitecbs.png",
    ],
  },
  {
    model: "BeAT",
    spec: {
      engineType: "	4 - Langkah, SOHC, eSP",
      displacement: "109,5 cc",
      maxPower: "6.6 kW (9.0 PS) / 7.500 rpm",
      maxTorque: "9.2 N.m (0.94 kgf.m) / 6000 rpm",
      brakingSystem: "Combi Brake System",
    },
    transmissionType: "Otomatis",
    keyless: false,
    price: 18,
    image: "/bikes/beat.png",
    colorVariant: [
      "/bikes/beat/black.png",
      "/bikes/beat/matteblack.png",
      "/bikes/beat/matteblue.png",
      "/bikes/beat/mattegreen.png",
      "/bikes/beat/mattesilver.png",
      "/bikes/beat/redblack.png",
      "/bikes/beat/rockblack.png",
      "/bikes/beat/whitblack.png",
    ],
  },
  {
    model: "BeAT Street",
    spec: {
      engineType: "4 Langkah, SOHC, eSP",
      displacement: "109,5 cc",
      maxPower: "6.6 kW (9.0 PS) / 7.500 rpm",
      maxTorque: "9.2 N.m (0.94 kgf.m) / 6000 rpm",
      brakingSystem: "Combi Brake System",
    },
    transmissionType: "Otomatis",
    keyless: false,
    price: 19,
    image: "/bikes/beat-street.png",
    colorVariant: [
      "/bikes/beat-street/brown.png",
      "/bikes/beat-street/black.png",
    ],
  },
  {
    model: "Genio",
    spec: {
      engineType: "4 – Langkah, SOHC, eSP",
      displacement: "109,5 cc",
      maxPower: "6,6 kW (9,0 PS) / 7.500 rpm",
      maxTorque: "9,3 Nm (0,95 kgf.m) / 5.500 rpm",
      brakingSystem: "Combi Brake System",
    },
    transmissionType: "Otomatis",
    keyless: false,
    price: 19,
    image: "/bikes/genio.png",
    colorVariant: [
      "/bikes/genio/fblack.png",
      "/bikes/genio/fblue.png",
      "/bikes/genio/fgreen.png",
      "/bikes/genio/rblack.png",
      "/bikes/genio/redblack.png",
      "/bikes/genio/rsblack.png",
    ],
  },
  {
    model: "Scoopy",
    spec: {
      engineType: "4 - Langkah, SOHC, eSP",
      displacement: "109,5 cc",
      maxPower: "6,6 kW (9 PS) / 7.500 rpm",
      maxTorque: "9,3 Nm (0,95 kgf.m) / 5.500 rpm",
      brakingSystem: "Combi Brake System",
    },
    transmissionType: "Otomatis",
    keyless: true,
    price: 22,
    image: "/bikes/scoopy.png",
    colorVariant: [
      "/bikes/scoopy/fblue.png",
      "/bikes/scoopy/fbrown.png",
      "/bikes/scoopy/pblack.png",
      "/bikes/scoopy/pwhite.png",
      "/bikes/scoopy/sgreen.png",
      "/bikes/scoopy/sgrey.png",
      "/bikes/scoopy/sred.png",
      "/bikes/scoopy/sreds.png",
    ],
  },
  {
    model: "Stylo 160",
    spec: {
      engineType: "	4 Langkah, 4 Katup, eSP+",
      displacement: "156,9 cc",
      maxPower: "11,3 kW (15,4 PS) / 8,500 rpm",
      maxTorque: "13,8 Nm (1,5 kgf.m) / 7000 rpm",
      brakingSystem: "CBS / ABS",
    },
    transmissionType: "Otomatis",
    keyless: true,
    price: 28,
    image: "/bikes/stylo.png",
    colorVariant: [
      "/bikes/stylo/gbeige.png",
      "/bikes/stylo/gblack.png",
      "/bikes/stylo/gred.png",
      "/bikes/stylo/mblack.png",
      "/bikes/stylo/mwhite.png",
      "/bikes/stylo/rgreen.png",
    ],
  },
  {
    model: "PCX 160",
    spec: {
      engineType: "4-Langkah, 4-Katup, eSP+",
      displacement: "156,9 cc",
      maxPower: "11,8 kW (16 PS) / 8.500 rpm",
      maxTorque: "14,7 Nm (1,5 kgf.m) / 6.500 rpm",
      brakingSystem: "CBS / ABS",
    },
    transmissionType: "Otomatis",
    keyless: true,
    price: 33,
    image: "/bikes/pcx.png",
    colorVariant: [
      "/bikes/pcx/bblack.png",
      "/bikes/pcx/mblack.png",
      "/bikes/pcx/mblue.png",
      "/bikes/pcx/mbrown.png",
      "/bikes/pcx/mmred.png",
      "/bikes/pcx/mred.png",
      "/bikes/pcx/msilver.png",
      "/bikes/pcx/rmblue.png",
      "/bikes/pcx/wwhite.png",
      "/bikes/pcx/wwhitecbs.png",
    ],
  },
  {
    model: "ADV 160",
    spec: {
      engineType: "4-Langkah, 4-Katup, eSP+",
      displacement: "156,9 cc",
      maxPower: "11,8 kW (16 PS) / 8.500 rpm",
      maxTorque: "14,7 Nm (1,5 kgf.m) / 6.500 rpm",
      brakingSystem: "CBS / ABS",
    },
    transmissionType: "Otomatis",
    keyless: true,
    price: 36,
    image: "/bikes/adv.png",
    colorVariant: [
      "/bikes/adv/dblack.png",
      "/bikes/adv/dgray.png",
      "/bikes/adv/dred.png",
      "/bikes/adv/dwhite.png",
      "/bikes/adv/mblack.png",
      "/bikes/adv/mbrown.png",
      "/bikes/adv/mred.png",
      "/bikes/adv/mwhite.png",
    ],
  },
  {
    model: "Forza",
    spec: {
      engineType: "eSP+, 4-katup, 4-langkah, SOHC",
      displacement: 249,
      maxPower: "17 kW / 7,750 rpm",
      maxTorque: "24 Nm / 6,250 rpm",
      brakingSystem: "Anti-Lock Braking System (ABS)",
    },
    keyless: true,
    price: 90,
    image: "/bikes/forza.png",
    colorVariant: [
      "/bikes/forza/black.png",
      "/bikes/forza/blue.png",
      "/bikes/forza/grey.png",
      "/bikes/forza/red.png",
    ],
  },
];

export const evBike = [
  {
    model: "ICON e:",
    spec: {
      maxPower: "1,7 kW/540 rpm",
      maxTorque: "90 Nm/25 rpm",
      ratedPower: "0,58 kW",
      brakingSystem: "Combi Brake System (CBS)",
    },
    transmissionType: "Otomatis",
    keyless: true,
    price: 28,
    image: "/bikes/icon.png",
    colorVariant: [
      "/bikes/icon/black.png",
      "/bikes/icon/mint.png",
      "/bikes/icon/orange.png",
      "/bikes/icon/red.png",
      "/bikes/icon/white.png",
    ],
  },
  {
    model: "EM1 e: & EM1 e: PLUS",
    spec: {
      maxPower: "1.81 kW / 618 rpm",
      maxTorque: "85 Nm / 110 rpm",
      ratedPower: "1.5 kW",
      brakingSystem: "Combi Brake System (CBS)",
    },
    transmissionType: "Otomatis",
    keyless: true,
    price: 40,
    image: "/bikes/em1.png",
    colorVariant: [
      "/bikes/em1/mblack.png",
      "/bikes/em1/msilver.png",
      "/bikes/em1/sred.png",
      "/bikes/em1/white.png",
    ],
  },
  {
    model: "CUV e: & RoadSync Duo",
    spec: {
      maxPower: "1.81 kW / 618 rpm",
      maxTorque: "85 Nm / 110 rpm",
      ratedPower: "1.5 kW",
      brakingSystem: "Combi Brake System (CBS)",
    },
    transmissionType: "Otomatis",
    keyless: true,
    price: 53,
    image: "/bikes/cuv.png",
    colorVariant: [
      "/bikes/cuv/mblack.png",
      "/bikes/cuv/msilver.png",
      "/bikes/cuv/mwhite.png",
      "/bikes/cuv/qmblack.png",
      "/bikes/cuv/qmsilver.png",
      "/bikes/cuv/qmwhite.png",
    ],
  },
];

export const sportBike = [
  {
    model: "CB150 Verza",
    spec: {
      engineType: "4 langkah, SOHC, Satu Silinder",
      displacement: "149.15 cc",
      maxPower: "9,59kW (13,04 PS) / 8.500 rpm",
      maxTorque: "12,73 Nm (1,30 kgf.m) / 6.000 rpm",
      frontBrake: "Cakram Hidrolik, Piston Ganda",
      rearBrake: "Tromol",
    },
    transmissionType: "Manual",
    keyless: true,
    price: 22,
    image: "/bikes/verza.png",
    colorVariant: [
      "/bikes/verza/black.png",
      "/bikes/verza/red.png",
      "/bikes/verza/mblack.png",
    ],
  },
  {
    model: "CB150R Streetfire",
    spec: {
      engineType: "4 Langkah, DOHC 4 Katup",
      displacement: "149,16 cc",
      maxPower: "12,4 kW (16,9 PS) / 9.000 rpm",
      maxTorque: "14,5 Nm (1,48 kgf.m) / 7.000 rpm",
      frontBrake: "Wavy Disc Brake",
      rearBrake: "Wavy Disc Brake",
    },
    transmissionType: "Manual",
    keyless: true,
    price: 31,
    image: "/bikes/cb150r.png",
    colorVariant: [
      "/bikes/cb150r/black.png",
      "/bikes/cb150r/mblack.png",
      "/bikes/cb150r/mgrey.png",
      "/bikes/cb150r/mred.png",
      "/bikes/cb150r/rblack.png",
    ],
  },
  {
    model: "CB150X",
    spec: {
      engineType: "4 Langkah, DOHC 4 Katup",
      displacement: "149,16 cc",
      maxPower: "11,5 kW (15,6 PS) / 9.000 rpm",
      maxTorque: "13,8 Nm (1,41 kgf.m) / 7.000 rpm",
      frontBrake: "Wavy Disc Brake",
      rearBrake: "Wavy Disc Brake",
    },
    transmissionType: "Manual",
    keyless: true,
    price: 34,
    image: "/bikes/cb150x.png",
    colorVariant: [
      "/bikes/cb150x/mblack.png",
      "/bikes/cb150x/mbrown.png",
      "/bikes/cb150x/mgreen.png",
      "/bikes/cb150x/red.png",
    ],
  },
  {
    model: "CRF150L",
    spec: {
      engineType: "4-Langkah, SOHC, Satu Silinder",
      displacement: "149.15 cc",
      maxPower: "9.51 kW (12.91 PS) / 8,000 rpm",
      maxTorque: "12.43 Nm (1.27 kgf.m) / 6,500 rpm",
      frontBrake: "Cakram Hidrolik (Wavy Disc, 240 mm)",
      rearBrake: "Cakram Hidrolik (Wavy Disc, 240 mm)",
    },
    transmissionType: "Manual",
    keyless: false,
    price: 37,
    image: "/bikes/crf150l.png",
    colorVariant: [
      "/bikes/crf150l/red.png",
      "/bikes/crf150l/black.png",
      "/bikes/crf150l/white.png",
      "/bikes/crf150l/green.png",
    ],
  },
  {
    model: "CBR150R",
    spec: {
      engineType: "4-Stroke, DOHC",
      displacement: "149,16 cc",
      maxPower: "12.6 kW (17.1 PS / 9,000 rpm)",
      maxTorque: "14.4 Nm (1.47 kgf.m / 7,000 rpm)",
      frontBrake: "Wavy Disc Brake",
      rearBrake: "Wavy Disc Brake",
    },
    transmissionType: "Manual",
    keyless: false,
    price: 38,
    image: "/bikes/cbr150r.png",
    colorVariant: [
      "/bikes/cbr150r/red.png",
      "/bikes/cbr150r/tricolor.png",
      "/bikes/cbr150r/black.png",
    ],
  },
  {
    model: "CBR250RR",
    spec: {
      engineType: "4-Stroke, 8-Valve, Parallel Twin Cylinder",
      displacement: "249.7 cc",
      maxPower: "31 kW (42 PS) / 13,000 rpm (SP | SP QS)",
      maxTorque: "25 Nm (2.5 kgf.m) / 11,000 rpm (SP | SP QS)",
      frontBrake: "Hydraulic Disc, Dual Piston",
      rearBrake: "Hydraulic Disc, Single Piston",
    },
    transmissionType: "Manual",
    keyless: false,
    price: 64,
    image: "/bikes/cbr250rr.png",
    colorVariant: [
      "/bikes/cbr250rr/red.png",
      "/bikes/cbr250rr/redblack.png",
      "/bikes/cbr250rr/tricolor.png",
      "/bikes/cbr250rr/black.png",
      "/bikes/cbr250rr/matteblack.png",
      "/bikes/cbr250rr/blue.png",
    ],
  },
  {
    model: "CRF250 Rally",
    spec: {
      engineType: "4-Stroke DOHC 4-valve Single Cylinder",
      displacement: "249.6 cc",
      maxPower: "18.9 kW / 8,500 rpm",
      maxTorque: "23.1 Nm / 6,500 rpm",
      frontBrake: "Floating Wave Disc with Dual-Piston Calipers",
      rearBrake: "Wave Disc with Single-Piston Calipers",
    },
    transmissionType: "Manual",
    keyless: false,
    price: 93,
    image: "/bikes/crf250rally.png",
    colorVariant: ["/bikes/crf250rally/red.png", "/bikes/crf250rally/red.png"],
  },
  {
    model: "CRF250L",
    spec: {
      engineType: "4-Stroke DOHC 4-valve Single Cylinder",
      displacement: "249.67 cc",
      maxPower: "18.9 kW / 8,500 rpm",
      maxTorque: "23.1 Nm / 6,500 rpm",
      frontBrake: "Wavy Disc Brake, Dual Piston Calipers",
      rearBrake: "Wavy Disc Brake, Single Piston Calipers",
    },
    transmissionType: "Manual",
    keyless: false,
    price: 79,
    image: "/bikes/crf250l.png",
    colorVariant: ["/bikes/crf250l/red.png", "/bikes/crf250l/red.png"],
  },
];

export const cubBike = [
  {
    model: "Revo",
    spec: {
      engineType: "SOHC, 4 Langkah, SOHC, Silinder Tunggal",
      displacement: "109.17 cc",
      maxPower: "6,56kW (8,91 PS) / 7.500 rpm",
      maxTorque: "8,76 Nm (0,86 kgf.m) / 6.000 rpm",
      frontBrake: "Cakram Hidrolik, Piston Tunggal",
      rearBrake: "Tromol",
    },
    transmissionType: "Manual",
    keyless: true,
    price: 16,
    image: "/bikes/revo.png",
    colorVariant: [
      "/bikes/revo/ared.png",
      "/bikes/revo/black.png",
      "/bikes/revo/blue.png",
      "/bikes/revo/red.png",
    ],
  },
  {
    model: "Supra X 125 FI",
    spec: {
      engineType: "4-Langkah, SOHC, Silinder Tunggal",
      displacement: "124,89 cc",
      maxPower: "7,40 kW (10,1 PS) / 8.000 rpm",
      maxTorque: "9,30 Nm (0,95 kgf.m) / 4.000 rpm",
      frontBrake: "Cakram Hidrolik dengan Piston Tunggal",
      rearBrake: "Cakram Hidrolik dengan Piston Tunggal",
    },
    transmissionType: "Manual",
    keyless: true,
    price: 19,
    image: "/bikes/suprax.png",
    colorVariant: [
      "/bikes/suprax/black.png",
      "/bikes/suprax/mblack.png",
      "/bikes/suprax/red.png",
    ],
  },
  {
    model: "GTR 150",
    spec: {
      engineType: "4-Langkah, DOHC, 4 Katup",
      displacement: "149,16 cc",
      maxPower: "12,0 kW (16,3 PS) / 9.000 rpm",
      maxTorque: "14,2 Nm (1,45 kgf.m) / 6.500 rpm",
      frontBrake: "Cakram Hidrolik",
      rearBrake: "Cakram Hidrolik",
    },
    transmissionType: "Manual",
    keyless: true,
    price: 25,
    image: "/bikes/supragtr.png",
    colorVariant: [
      "/bikes/supragtr/black.png",
      "/bikes/supragtr/mred.png",
      "/bikes/supragtr/msilver.png",
      "/bikes/supragtr/red.png",
    ],
  },
  {
    model: "C125",
    spec: {
      engineType: "4-stroke SOHC 2-Valve",
      displacement: "124 cc",
      maxPower: "7,2 kW / 7.500 rpm",
      maxTorque: "10,4 nM / 6.250 rpm",
      frontBrake: "Hydraulic Disc",
      rearBrake: "Mechanical Leading Trailing",
    },
    transmissionType: "Manual",
    keyless: true,
    price: 77,
    image: "/bikes/c125.png",
    colorVariant: [
      "/bikes/c125/mattegray.png",
      "/bikes/c125/pearlgray.png",
      "/bikes/c125/pearlred.png",
    ],
  },
  {
    model: "CT125",
    spec: {
      engineType: "Air-Cooled, 4-Stroke, SOHC Single Cylinder",
      displacement: "124 cc",
      maxPower: "6,76 kW / 6250 rpm",
      maxTorque: "10,8 Nm/4.750 rpm",
      frontBrake: "220mm Hydraulic Disc",
      rearBrake: "190mm Hydraulic Disc",
    },
    keyless: true,
    price: 81,
    image: "/bikes/ct125.png",
    colorVariant: ["/bikes/ct125/red.png", "/bikes/ct125/red.png"],
  },
];

export const bikeType = [
  {
    title: "Tipe",
    value: "",
  },
  {
    title: "Matic",
    value: "Matic",
  },
  {
    title: "Sport",
    value: "Sport",
  },
  {
    title: "Cub",
    value: "Cub",
  },
  {
    title: "Ev",
    value: "Ev",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
